// CRM Assistant - talks only to our own localhost:8420 /api/chat, which in
// turn talks only to a local Ollama model. No CRM data ever leaves this
// machine. Read-only: this page cannot write anything to Zoho.

const state = { history: [] };

const SUGGESTIONS = [
  'How many leads do we have and what%27s our conversion rate?',
  'Which rep has the highest revenue this year?',
  'How is the open pipeline looking by pipeline?',
  'What deals need attention right now?',
  'How are we tracking against this month%27s revenue target?',
];

const esc = (s) => String(s ?? '').replace(/[&<>"]/g,
  (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

// The model can misstate a number even when the tool data behind it is
// correct (verified: it has mis-transcribed a correctly pre-formatted
// figure). So every reply that used a tool shows the real returned data
// too, not just the model's prose - that's the actual source of truth.
function renderValue(v) {
  if (v === null || v === undefined) return '—';
  if (typeof v === 'object') return esc(JSON.stringify(v));
  return esc(String(v));
}

function renderFact(obj) {
  const entries = Object.entries(obj).filter(([k]) => !k.endsWith('_inr'));
  return `<table>${entries.map(([k, v]) =>
    `<tr><td class="fact-key">${esc(k.replace(/_/g, ' '))}</td><td>${renderValue(v)}</td></tr>`).join('')}</table>`;
}

function renderTable(rows) {
  if (!rows.length) return '<div class="empty">(no rows)</div>';
  const cols = Object.keys(rows[0]).filter(k => !k.endsWith('_inr'));
  return `<table><thead><tr>${cols.map(c => `<th>${esc(c.replace(/_/g, ' '))}</th>`).join('')}</tr></thead>
    <tbody>${rows.slice(0, 8).map(r => `<tr>${cols.map(c => `<td>${renderValue(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
}

function renderToolData(toolCalls) {
  if (!toolCalls || !toolCalls.length) return '';
  return toolCalls.map(({ tool, data }) => {
    if (!data || typeof data !== 'object') return '';
    const sections = Object.entries(data).map(([key, value]) => {
      if (Array.isArray(value)) return `<div class="fact-label">${esc(key.replace(/_/g, ' '))}</div>${renderTable(value)}`;
      if (value && typeof value === 'object') return `<div class="fact-label">${esc(key.replace(/_/g, ' '))}</div>${renderFact(value)}`;
      if (key.endsWith('_inr')) return '';
      return `<div class="fact-row"><span class="fact-label">${esc(key.replace(/_/g, ' '))}:</span> ${renderValue(value)}</div>`;
    }).join('');
    return `<details class="verified-data"><summary>Verified data from <code>${esc(tool)}</code></summary>${sections}</details>`;
  }).join('');
}

function addMessage(role, text, { thinking = false, toolCalls = null, error = false, headline = null } = {}) {
  const log = document.getElementById('chat-log');
  const wrap = document.createElement('div');
  wrap.className = `msg ${role}`;
  const bubbleClasses = ['bubble', thinking ? 'thinking' : '', error ? 'error' : ''].filter(Boolean).join(' ');
  const trace = toolCalls && toolCalls.length
    ? `<div class="tool-trace">checked: ${toolCalls.map(t => esc(t.tool)).join(', ')}</div>${renderToolData(toolCalls)}`
    : '';
  // The headline (if any) is code-computed from verified data - guaranteed
  // correct. The model's own sentence goes below it as commentary/context;
  // it has mis-stated a specific figure even when everything else about
  // the answer was right, so it is never the sole source for a number.
  const headlineHtml = headline
    ? `<div class="headline">${esc(headline)}</div><div class="headline-note">the figure above is computed directly, not generated by the model</div>`
    : '';
  wrap.innerHTML = `${headlineHtml}<div class="${bubbleClasses}">${esc(text)}</div>${trace}`;
  log.appendChild(wrap);
  log.scrollTop = log.scrollHeight;
  return wrap;
}

async function send(message) {
  if (!message.trim()) return;
  addMessage('user', message);
  const sendBtn = document.getElementById('chat-send');
  sendBtn.disabled = true;
  const thinkingEl = addMessage('bot', 'Thinking', { thinking: true });

  try {
    const res = await fetch('/api/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message, history: state.history }),
    });
    const data = await res.json();
    thinkingEl.remove();

    if (!res.ok || data.error) {
      addMessage('bot', data.error || `Request failed (${res.status})`, { error: true });
      return;
    }

    addMessage('bot', data.reply, { toolCalls: data.tool_calls || [], headline: data.headline });
    state.history.push({ role: 'user', content: message });
    state.history.push({ role: 'assistant', content: data.reply });
    // Keep history bounded so the local model isn't fed an ever-growing prompt.
    if (state.history.length > 16) state.history = state.history.slice(-16);
  } catch (e) {
    thinkingEl.remove();
    addMessage('bot', `Couldn't reach the API: ${e.message}`, { error: true });
  } finally {
    sendBtn.disabled = false;
  }
}

document.getElementById('chat-form').addEventListener('submit', (e) => {
  e.preventDefault();
  const textEl = document.getElementById('chat-text');
  const text = textEl.value;
  textEl.value = '';
  textEl.style.height = 'auto';
  send(text);
});

document.getElementById('chat-text').addEventListener('input', (e) => {
  e.target.style.height = 'auto';
  e.target.style.height = Math.min(e.target.scrollHeight, 120) + 'px';
});
document.getElementById('chat-text').addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    document.getElementById('chat-form').requestSubmit();
  }
});

document.getElementById('suggestions').innerHTML = SUGGESTIONS
  .map(s => `<button type="button">${esc(decodeURIComponent(s.replace(/%27/g, "'")))}</button>`).join('');
document.querySelectorAll('.suggestions button').forEach(btn => {
  btn.addEventListener('click', () => send(btn.textContent));
});

async function checkStatus() {
  const el = document.getElementById('sync-status');
  try {
    const res = await fetch('/api/meta');
    if (!res.ok) throw new Error();
    el.textContent = 'API connected';
    el.classList.replace('pill-muted', 'pill-good');
  } catch {
    el.textContent = 'API unreachable — run: python scripts/serve.py';
  }
}

// Convenience for testing/linking: ?q=<question> auto-sends on load.
const preset = new URLSearchParams(location.search).get('q');
if (preset) send(preset);
checkStatus();
